/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_require = 1,
  anon_sym_as = 2,
  anon_sym_add = 3,
  anon_sym_all = 4,
  anon_sym_from = 5,
  anon_sym_hide = 6,
  anon_sym_is = 7,
  anon_sym_contains = 8,
  anon_sym_where = 9,
  anon_sym_or = 10,
  sym_identifier = 11,
  sym_comment = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  sym_source_file = 15,
  sym__statement = 16,
  sym_require_statement = 17,
  sym_addFrom_statement = 18,
  sym_hide_statement = 19,
  sym_filter = 20,
  sym_whereContains_statement = 21,
  sym_string = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_require_statement_repeat1 = 24,
  aux_sym_whereContains_statement_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_require] = "require",
  [anon_sym_as] = "as",
  [anon_sym_add] = "add",
  [anon_sym_all] = "all",
  [anon_sym_from] = "from",
  [anon_sym_hide] = "hide",
  [anon_sym_is] = "is",
  [anon_sym_contains] = "contains",
  [anon_sym_where] = "where",
  [anon_sym_or] = "or",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_require_statement] = "require_statement",
  [sym_addFrom_statement] = "addFrom_statement",
  [sym_hide_statement] = "hide_statement",
  [sym_filter] = "filter",
  [sym_whereContains_statement] = "whereContains_statement",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_require_statement_repeat1] = "require_statement_repeat1",
  [aux_sym_whereContains_statement_repeat1] = "whereContains_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_require] = anon_sym_require,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_hide] = anon_sym_hide,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_contains] = anon_sym_contains,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_or] = anon_sym_or,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_require_statement] = sym_require_statement,
  [sym_addFrom_statement] = sym_addFrom_statement,
  [sym_hide_statement] = sym_hide_statement,
  [sym_filter] = sym_filter,
  [sym_whereContains_statement] = sym_whereContains_statement,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_require_statement_repeat1] = aux_sym_require_statement_repeat1,
  [aux_sym_whereContains_statement_repeat1] = aux_sym_whereContains_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_require] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hide] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contains] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_require_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_addFrom_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_hide_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_whereContains_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_require_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_whereContains_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 61,
        ';', 60,
        'a', 2,
        'c', 18,
        'f', 22,
        'h', 11,
        'i', 25,
        'o', 21,
        'r', 5,
        'w', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(4);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'q') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(1);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 29:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      if (lookahead == ';') ADVANCE(60);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == 'h') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == ';') ADVANCE(60);
      if (lookahead == 'a') ADVANCE(48);
      if (lookahead == 'h') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_require);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_require);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_add);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_hide);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_hide);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_contains);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == 's') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(52);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(50);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'q') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(63);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 31},
  [8] = {.lex_state = 31},
  [9] = {.lex_state = 31},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 31},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 62},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_require] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_hide] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_contains] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym__statement] = STATE(3),
    [sym_require_statement] = STATE(3),
    [sym_addFrom_statement] = STATE(3),
    [sym_hide_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_require] = ACTIONS(5),
    [anon_sym_add] = ACTIONS(7),
    [anon_sym_hide] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_require,
    ACTIONS(18), 1,
      anon_sym_add,
    ACTIONS(21), 1,
      anon_sym_hide,
    ACTIONS(24), 1,
      sym_comment,
    STATE(2), 5,
      sym__statement,
      sym_require_statement,
      sym_addFrom_statement,
      sym_hide_statement,
      aux_sym_source_file_repeat1,
  [23] = 6,
    ACTIONS(5), 1,
      anon_sym_require,
    ACTIONS(7), 1,
      anon_sym_add,
    ACTIONS(9), 1,
      anon_sym_hide,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_comment,
    STATE(2), 5,
      sym__statement,
      sym_require_statement,
      sym_addFrom_statement,
      sym_hide_statement,
      aux_sym_source_file_repeat1,
  [46] = 1,
    ACTIONS(31), 8,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      anon_sym_is,
      anon_sym_contains,
      anon_sym_or,
      sym_comment,
  [57] = 1,
    ACTIONS(33), 8,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      anon_sym_is,
      anon_sym_contains,
      anon_sym_or,
      sym_comment,
  [68] = 3,
    ACTIONS(39), 1,
      anon_sym_as,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(37), 4,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_identifier,
  [82] = 4,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(8), 1,
      aux_sym_require_statement_repeat1,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(43), 3,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
  [98] = 4,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(9), 1,
      aux_sym_require_statement_repeat1,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(49), 3,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
  [114] = 4,
    ACTIONS(55), 1,
      sym_identifier,
    STATE(9), 1,
      aux_sym_require_statement_repeat1,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(53), 3,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
  [130] = 3,
    ACTIONS(60), 1,
      anon_sym_or,
    STATE(12), 1,
      aux_sym_whereContains_statement_repeat1,
    ACTIONS(58), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [144] = 3,
    ACTIONS(64), 1,
      anon_sym_where,
    STATE(17), 1,
      sym_whereContains_statement,
    ACTIONS(62), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [158] = 3,
    ACTIONS(60), 1,
      anon_sym_or,
    STATE(13), 1,
      aux_sym_whereContains_statement_repeat1,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [172] = 3,
    ACTIONS(70), 1,
      anon_sym_or,
    STATE(13), 1,
      aux_sym_whereContains_statement_repeat1,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [186] = 2,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(75), 4,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_identifier,
  [197] = 1,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      anon_sym_or,
      sym_comment,
  [206] = 1,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [214] = 1,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [222] = 3,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      sym_filter,
    STATE(22), 1,
      sym_string,
  [232] = 3,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      sym_filter,
    STATE(22), 1,
      sym_string,
  [242] = 1,
    ACTIONS(83), 2,
      anon_sym_is,
      anon_sym_contains,
  [247] = 2,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      sym_string,
  [254] = 1,
    ACTIONS(85), 2,
      anon_sym_is,
      anon_sym_contains,
  [259] = 2,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym_string,
  [266] = 1,
    ACTIONS(87), 1,
      anon_sym_all,
  [270] = 1,
    ACTIONS(89), 1,
      sym_identifier,
  [274] = 1,
    ACTIONS(91), 1,
      anon_sym_from,
  [278] = 1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [282] = 1,
    ACTIONS(95), 1,
      sym_identifier,
  [286] = 1,
    ACTIONS(97), 1,
      sym_identifier,
  [290] = 1,
    ACTIONS(99), 1,
      aux_sym_string_token1,
  [294] = 1,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 82,
  [SMALL_STATE(8)] = 98,
  [SMALL_STATE(9)] = 114,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 144,
  [SMALL_STATE(12)] = 158,
  [SMALL_STATE(13)] = 172,
  [SMALL_STATE(14)] = 186,
  [SMALL_STATE(15)] = 197,
  [SMALL_STATE(16)] = 206,
  [SMALL_STATE(17)] = 214,
  [SMALL_STATE(18)] = 222,
  [SMALL_STATE(19)] = 232,
  [SMALL_STATE(20)] = 242,
  [SMALL_STATE(21)] = 247,
  [SMALL_STATE(22)] = 254,
  [SMALL_STATE(23)] = 259,
  [SMALL_STATE(24)] = 266,
  [SMALL_STATE(25)] = 270,
  [SMALL_STATE(26)] = 274,
  [SMALL_STATE(27)] = 278,
  [SMALL_STATE(28)] = 282,
  [SMALL_STATE(29)] = 286,
  [SMALL_STATE(30)] = 290,
  [SMALL_STATE(31)] = 294,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_require_statement_repeat1, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_statement, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_require_statement, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_statement, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_require_statement, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_require_statement_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whereContains_statement, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addFrom_statement, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whereContains_statement, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whereContains_statement_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whereContains_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_require_statement_repeat1, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hide_statement, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addFrom_statement, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zql(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zql",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
