/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_require = 1,
  anon_sym_as = 2,
  anon_sym_add = 3,
  anon_sym_all = 4,
  anon_sym_from = 5,
  anon_sym_hide = 6,
  anon_sym_where = 7,
  anon_sym_contains = 8,
  anon_sym_is = 9,
  anon_sym_or = 10,
  aux_sym_identifier_member_token1 = 11,
  sym_comment = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  sym_source_file = 15,
  sym__statement = 16,
  sym_require_statement = 17,
  sym_addFrom_statement = 18,
  sym_hide_statement = 19,
  sym_whereContains_statement = 20,
  sym_identifier_member = 21,
  sym_identifier = 22,
  sym_string = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_require_statement_repeat1 = 25,
  aux_sym_whereContains_statement_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_require] = "require",
  [anon_sym_as] = "as",
  [anon_sym_add] = "add",
  [anon_sym_all] = "all",
  [anon_sym_from] = "from",
  [anon_sym_hide] = "hide",
  [anon_sym_where] = "where",
  [anon_sym_contains] = "contains",
  [anon_sym_is] = "is",
  [anon_sym_or] = "or",
  [aux_sym_identifier_member_token1] = "identifier_member_token1",
  [sym_comment] = "comment",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_require_statement] = "require_statement",
  [sym_addFrom_statement] = "addFrom_statement",
  [sym_hide_statement] = "hide_statement",
  [sym_whereContains_statement] = "whereContains_statement",
  [sym_identifier_member] = "identifier_member",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_require_statement_repeat1] = "require_statement_repeat1",
  [aux_sym_whereContains_statement_repeat1] = "whereContains_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_require] = anon_sym_require,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_hide] = anon_sym_hide,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_contains] = anon_sym_contains,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_or] = anon_sym_or,
  [aux_sym_identifier_member_token1] = aux_sym_identifier_member_token1,
  [sym_comment] = sym_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_require_statement] = sym_require_statement,
  [sym_addFrom_statement] = sym_addFrom_statement,
  [sym_hide_statement] = sym_hide_statement,
  [sym_whereContains_statement] = sym_whereContains_statement,
  [sym_identifier_member] = sym_identifier_member,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_require_statement_repeat1] = aux_sym_require_statement_repeat1,
  [aux_sym_whereContains_statement_repeat1] = aux_sym_whereContains_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_require] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hide] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contains] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_member_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_require_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_addFrom_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_hide_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_whereContains_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_member] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_require_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_whereContains_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 7,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '"', 65,
        ';', 64,
        'a', 3,
        'c', 19,
        'f', 23,
        'h', 12,
        'i', 26,
        'o', 22,
        'r', 6,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 21:
      if (lookahead == 'q') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 30:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 31:
      if (eof) ADVANCE(33);
      if (lookahead == ';') ADVANCE(64);
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead == 'h') ADVANCE(57);
      if (lookahead == 'r') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == ';') ADVANCE(64);
      if (lookahead == 'a') ADVANCE(50);
      if (lookahead == 'h') ADVANCE(57);
      if (lookahead == 'r') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_require);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_require);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_add);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_all);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_hide);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_hide);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_contains);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'd') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == 's') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'd') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'i') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'i') ADVANCE(52);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'l') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'l') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'q') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'r') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == 'u') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_identifier_member_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(67);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 31},
  [5] = {.lex_state = 31},
  [6] = {.lex_state = 31},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 31},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 31},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 30},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 30},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 66},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_require] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_hide] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_contains] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(34),
    [sym__statement] = STATE(3),
    [sym_require_statement] = STATE(3),
    [sym_addFrom_statement] = STATE(3),
    [sym_hide_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_require] = ACTIONS(5),
    [anon_sym_add] = ACTIONS(7),
    [anon_sym_hide] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_require,
    ACTIONS(18), 1,
      anon_sym_add,
    ACTIONS(21), 1,
      anon_sym_hide,
    ACTIONS(24), 1,
      sym_comment,
    STATE(2), 5,
      sym__statement,
      sym_require_statement,
      sym_addFrom_statement,
      sym_hide_statement,
      aux_sym_source_file_repeat1,
  [23] = 6,
    ACTIONS(5), 1,
      anon_sym_require,
    ACTIONS(7), 1,
      anon_sym_add,
    ACTIONS(9), 1,
      anon_sym_hide,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_comment,
    STATE(2), 5,
      sym__statement,
      sym_require_statement,
      sym_addFrom_statement,
      sym_hide_statement,
      aux_sym_source_file_repeat1,
  [46] = 5,
    ACTIONS(35), 1,
      aux_sym_identifier_member_token1,
    STATE(4), 1,
      aux_sym_require_statement_repeat1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(33), 3,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
  [65] = 5,
    ACTIONS(42), 1,
      aux_sym_identifier_member_token1,
    STATE(4), 1,
      aux_sym_require_statement_repeat1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(40), 3,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
  [84] = 5,
    ACTIONS(42), 1,
      aux_sym_identifier_member_token1,
    STATE(5), 1,
      aux_sym_require_statement_repeat1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(46), 3,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
  [103] = 1,
    ACTIONS(48), 8,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_from,
      anon_sym_hide,
      anon_sym_where,
      anon_sym_contains,
      sym_comment,
  [114] = 2,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(50), 5,
      anon_sym_require,
      anon_sym_as,
      anon_sym_add,
      anon_sym_hide,
      aux_sym_identifier_member_token1,
  [126] = 3,
    ACTIONS(54), 1,
      anon_sym_where,
    STATE(18), 1,
      sym_whereContains_statement,
    ACTIONS(52), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [140] = 3,
    ACTIONS(58), 1,
      anon_sym_or,
    STATE(11), 1,
      aux_sym_whereContains_statement_repeat1,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [154] = 3,
    ACTIONS(58), 1,
      anon_sym_or,
    STATE(13), 1,
      aux_sym_whereContains_statement_repeat1,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [168] = 3,
    ACTIONS(66), 1,
      anon_sym_as,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(64), 4,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      aux_sym_identifier_member_token1,
  [182] = 3,
    ACTIONS(70), 1,
      anon_sym_or,
    STATE(13), 1,
      aux_sym_whereContains_statement_repeat1,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [196] = 1,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      anon_sym_or,
      sym_comment,
  [205] = 2,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(77), 4,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      aux_sym_identifier_member_token1,
  [216] = 1,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      anon_sym_or,
      sym_comment,
  [225] = 2,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      sym_comment,
    ACTIONS(50), 4,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      aux_sym_identifier_member_token1,
  [236] = 1,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [244] = 1,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_require,
      anon_sym_add,
      anon_sym_hide,
      sym_comment,
  [252] = 3,
    ACTIONS(85), 1,
      anon_sym_all,
    ACTIONS(87), 1,
      aux_sym_identifier_member_token1,
    STATE(31), 1,
      sym_identifier,
  [262] = 2,
    ACTIONS(89), 1,
      aux_sym_identifier_member_token1,
    STATE(24), 1,
      sym_identifier_member,
  [269] = 2,
    ACTIONS(91), 1,
      aux_sym_identifier_member_token1,
    STATE(9), 1,
      sym_identifier,
  [276] = 1,
    ACTIONS(93), 2,
      anon_sym_contains,
      anon_sym_is,
  [281] = 1,
    ACTIONS(95), 2,
      anon_sym_contains,
      anon_sym_is,
  [286] = 2,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      sym_string,
  [293] = 2,
    ACTIONS(91), 1,
      aux_sym_identifier_member_token1,
    STATE(19), 1,
      sym_identifier,
  [300] = 2,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
  [307] = 2,
    ACTIONS(99), 1,
      aux_sym_identifier_member_token1,
    STATE(15), 1,
      sym_identifier,
  [314] = 2,
    ACTIONS(91), 1,
      aux_sym_identifier_member_token1,
    STATE(33), 1,
      sym_identifier,
  [321] = 1,
    ACTIONS(101), 1,
      aux_sym_string_token1,
  [325] = 1,
    ACTIONS(103), 1,
      anon_sym_from,
  [329] = 1,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
  [333] = 1,
    ACTIONS(107), 1,
      anon_sym_contains,
  [337] = 1,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 65,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 103,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 126,
  [SMALL_STATE(10)] = 140,
  [SMALL_STATE(11)] = 154,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 182,
  [SMALL_STATE(14)] = 196,
  [SMALL_STATE(15)] = 205,
  [SMALL_STATE(16)] = 216,
  [SMALL_STATE(17)] = 225,
  [SMALL_STATE(18)] = 236,
  [SMALL_STATE(19)] = 244,
  [SMALL_STATE(20)] = 252,
  [SMALL_STATE(21)] = 262,
  [SMALL_STATE(22)] = 269,
  [SMALL_STATE(23)] = 276,
  [SMALL_STATE(24)] = 281,
  [SMALL_STATE(25)] = 286,
  [SMALL_STATE(26)] = 293,
  [SMALL_STATE(27)] = 300,
  [SMALL_STATE(28)] = 307,
  [SMALL_STATE(29)] = 314,
  [SMALL_STATE(30)] = 321,
  [SMALL_STATE(31)] = 325,
  [SMALL_STATE(32)] = 329,
  [SMALL_STATE(33)] = 333,
  [SMALL_STATE(34)] = 337,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_require_statement_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_statement, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_require_statement, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_statement, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_require_statement, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addFrom_statement, 4, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whereContains_statement, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whereContains_statement, 5, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_require_statement_repeat1, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whereContains_statement_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whereContains_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_require_statement_repeat1, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_statement_repeat1, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whereContains_statement_repeat1, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addFrom_statement, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hide_statement, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_member, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [109] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zql(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zql",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
